version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    # Use a bind mount to replace the nginx configure file
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  # Use a Mongo database to store general application data
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=standard
    volumes:
      # Save data to a named volume ("mongo-db")
      - mongo-db:/data/db

  # Use a redis database for session authentication
  redis:
    image: redis

volumes:
  mongo-db:
  

# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
# To bash into mongo container while running:
#   docker exec -it node_docker_mongo_1 mongo -u "admin" -p "standard"
    